from __future__ import annotations

import os
import sqlite3
from pathlib import Path
from typing import Any

try:
    import psycopg
    from psycopg.rows import dict_row
except ImportError:  # Local SQLite fallback can run before Postgres deps are installed.
    psycopg = None
    dict_row = None

INTEGRITY_ERRORS = (
    (sqlite3.IntegrityError, psycopg.IntegrityError)
    if psycopg is not None
    else (sqlite3.IntegrityError,)
)

BASE_DIR = Path(__file__).resolve().parents[2]
DB_PATH = BASE_DIR / "jppilot0002.db"
DATABASE_URL = os.getenv("DATABASE_URL", "")


class AppConnection:
    def __init__(self, conn: Any, backend: str) -> None:
        self.conn = conn
        self.backend = backend

    def __enter__(self) -> "AppConnection":
        self.conn.__enter__()
        return self

    def __exit__(self, exc_type: Any, exc: Any, tb: Any) -> None:
        return self.conn.__exit__(exc_type, exc, tb)

    def execute(self, sql: str, params: tuple[Any, ...] | list[Any] = ()) -> Any:
        if self.backend == "postgres":
            sql = sql.replace("?", "%s")
            return ResultAdapter(self.conn.execute(sql, params))
        return self.conn.execute(sql, params)

    def close(self) -> None:
        self.conn.close()


class RowDict(dict):
    def __getitem__(self, key: Any) -> Any:
        if isinstance(key, int):
            return list(self.values())[key]
        return super().__getitem__(key)


class ResultAdapter:
    def __init__(self, cursor: Any) -> None:
        self.cursor = cursor

    @property
    def rowcount(self) -> int:
        return self.cursor.rowcount

    def fetchone(self) -> Any:
        row = self.cursor.fetchone()
        return RowDict(row) if isinstance(row, dict) else row

    def fetchall(self) -> list[Any]:
        return [RowDict(row) if isinstance(row, dict) else row for row in self.cursor.fetchall()]


def use_postgres() -> bool:
    return bool(DATABASE_URL)


def get_conn() -> AppConnection:
    if use_postgres():
        if psycopg is None or dict_row is None:
            raise RuntimeError("DATABASE_URL is set, but psycopg is not installed.")
        return AppConnection(psycopg.connect(DATABASE_URL, row_factory=dict_row), "postgres")

    conn = sqlite3.connect(str(DB_PATH))
    conn.row_factory = sqlite3.Row
    conn.execute("PRAGMA foreign_keys = ON")
    return AppConnection(conn, "sqlite")


def init_db() -> None:
    if use_postgres():
        init_postgres()
    else:
        init_sqlite()


def init_sqlite() -> None:
    with get_conn() as conn:
        conn.execute("""
        CREATE TABLE IF NOT EXISTS words (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            japanese TEXT NOT NULL,
            reading TEXT DEFAULT '',
            meaning_en TEXT NOT NULL,
            meaning_ko TEXT DEFAULT '',
            part_of_speech TEXT DEFAULT '',
            jlpt_level TEXT DEFAULT 'N2',
            difficulty INTEGER DEFAULT 3,
            tags TEXT DEFAULT '',
            example_jp TEXT DEFAULT '',
            example_en TEXT DEFAULT '',
            example_ko TEXT DEFAULT '',
            note TEXT DEFAULT '',
            source TEXT DEFAULT 'manual',
            review_status TEXT DEFAULT 'new',
            review_count INTEGER DEFAULT 0,
            correct_count INTEGER DEFAULT 0,
            wrong_count INTEGER DEFAULT 0,
            interval_days INTEGER DEFAULT 0,
            ease_factor REAL DEFAULT 2.5,
            next_review_at TEXT DEFAULT '',
            last_reviewed_at TEXT DEFAULT '',
            created_at TEXT NOT NULL,
            updated_at TEXT NOT NULL,
            UNIQUE(japanese, reading, meaning_en)
        )
        """)

        conn.execute("""
        CREATE TABLE IF NOT EXISTS study_logs (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            word_id INTEGER NOT NULL,
            mode TEXT NOT NULL,
            result TEXT NOT NULL,
            created_at TEXT NOT NULL,
            FOREIGN KEY(word_id) REFERENCES words(id) ON DELETE CASCADE
        )
        """)


def init_postgres() -> None:
    with get_conn() as conn:
        conn.execute("""
        CREATE TABLE IF NOT EXISTS words (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            japanese TEXT NOT NULL,
            reading TEXT DEFAULT '',
            meaning_en TEXT NOT NULL,
            meaning_ko TEXT DEFAULT '',
            part_of_speech TEXT DEFAULT '',
            jlpt_level TEXT DEFAULT 'N2',
            difficulty INTEGER DEFAULT 3,
            tags TEXT DEFAULT '',
            example_jp TEXT DEFAULT '',
            example_en TEXT DEFAULT '',
            example_ko TEXT DEFAULT '',
            note TEXT DEFAULT '',
            source TEXT DEFAULT 'manual',
            review_status TEXT DEFAULT 'new',
            review_count INTEGER DEFAULT 0,
            correct_count INTEGER DEFAULT 0,
            wrong_count INTEGER DEFAULT 0,
            interval_days INTEGER DEFAULT 0,
            ease_factor DOUBLE PRECISION DEFAULT 2.5,
            next_review_at TEXT DEFAULT '',
            last_reviewed_at TEXT DEFAULT '',
            created_at TEXT NOT NULL,
            updated_at TEXT NOT NULL,
            UNIQUE(japanese, reading, meaning_en)
        )
        """)

        conn.execute("""
        CREATE TABLE IF NOT EXISTS study_logs (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            word_id INTEGER NOT NULL,
            mode TEXT NOT NULL,
            result TEXT NOT NULL,
            created_at TEXT NOT NULL,
            FOREIGN KEY(word_id) REFERENCES words(id) ON DELETE CASCADE
        )
        """)
